config/routes.rb
Rails.application.routes.draw do
  get 'answer', to: 'questions#answer'
  get 'ask', to: 'questions#ask', as: :ask
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end

  def answer
    if params[:user_question][-1, 1] == "?"
      @answer = "Silly question, get dressed and go to work!"
    elsif params[:user_question] == "I am going to work"
      @answer = "Great!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
    return @answer
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><em>Stupid Coaching</em></h1>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="question">
  <p><%= params[:user_question] %></p>
  <p><em>-You</em></p>
</div>

<div class="answer"><p>
  <p><%= @answer %></p>
  <em>-Coach</em></p>
</div>

<div class="link">
  <br>
  <%= link_to "Ask again", ask_path %>
  <br>
</div>

app/views/questions/ask.html.erb
<h2>Talk to Coach!</h2>
<form action="/answer" method="get">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="user_question" id="field">
  <input type="submit" value="Ask!">
</form>